### ISSUE TITLE
coding: Design a Profile Page.

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#67] opened 2021-03-12 06:17 UTC
## Is your feature request related to a problem? Please describe.
Create a Profile Page for the website which includes Name, Username, Avatar, About me(text box)

## Describe the solution you'd like
Design and show its screenshot

## Additional context
Approval of 2 mentors required

**Comment by ritesh1731** [comment] 2021-03-12 10:11
I would like to contribute to this issue under GSSOC21. Can you please assign it to me?

**Comment by khushishikhu** [comment] 2021-03-12 10:26
@ritesh1731 assigning this to you

**Comment by ritesh1731** [comment] 2021-03-14 12:31
Sorry for the delay. Actually, I was busy with the college exams. I will start working on this issue from today.

**Comment by Nidhikamewar15** [comment] 2021-03-14 12:42
@khushishikhu    I can work on this issue with @ritesh1731  if he is fine with it and if you approve so?

**Comment by ritesh1731** [comment] 2021-03-14 12:46
@Nidhikamewar15  It is fine by me. We can work together on this issue if @khushishikhu  approves.

**Comment by khushishikhu** [comment] 2021-03-14 13:34
@Nidhikamewar15 ohk , assigning this to you too . Happy Coding ✌️

**Comment by ritesh1731** [comment] 2021-03-16 10:54
Here are some of the designs for the profile page. Please review them so that I can make changes if require and start coding.

**Comment by khushishikhu** [comment] 2021-03-16 11:00
@ritesh1731 @Nidhikamewar15  I found the first design impressive 😍. You can start working on making this as our profile page🎉

**Comment by RiaKokate** [comment] 2021-03-16 14:25
Hello @khushishikhu .
I hope you are safe and doing well.
I would like to work on this task. Could you please assign it to me?

**Comment by A-HK** [comment] 2021-04-17 20:08
Hey @khushishikhu @Aaishpra ,if nobody else is currently interested, can I work on implementing this next?

**Comment by Aaishpra** [comment] 2021-04-18 02:33
@ritesh1731 any updates on this

**Comment by A-HK** [comment] 2021-04-19 07:09
@khushishikhu @Aaishpra , would love to know if I can go ahead with this.

**Comment by Aaishpra** [comment] 2021-04-19 07:15
@A-HK assigned you here.

**Comment by A-HK** [comment] 2021-04-19 07:20
Should I follow the above design or make my own?

**Comment by Aaishpra** [comment] 2021-04-19 07:44
I like the design presented here, so if you can follow that it would be great! But feel free to change anything according to your choice.

**Comment by anushka-srivastava22** [comment] 2021-05-03 15:26
I am gssoc participant. Can I work upon this issue. I would love to contribute to it.

**Comment by A-HK** [comment] 2021-05-03 16:19
Hey @anushka-srivastava22 @Aaishpra , still trying to work on this!

Spent the last few days debugging my application, but still coming across a few errors

**Comment by A-HK** [comment] 2021-05-03 16:23
![image](https://user-images.githubusercontent.com/73497800/116903219-bc879100-ac59-11eb-9e7b-749d938e97f0.png)

This is the error it's throwing. Do you have any idea as to what might be causing it @khushishikhu @Aaishpra ?

So sorry for taking up your time.

**Comment by Aaishpra** [comment] 2021-05-04 04:49
Hi, @A-HK can you share your code, then we can look into this more.

**Comment by A-HK** [comment] 2021-05-06 13:54
I sure will, thanks!

Meanwhile, do you have any suggestions/criticisms for this profile page?
![periodo_profile_page](https://user-images.githubusercontent.com/73497800/117309975-8e47c280-aea0-11eb-8b66-3c140815a569.png)

**Comment by Aaishpra** [comment] 2021-05-06 15:04
Well this simply looks great @A-HK , I have no problem with this

**Comment by A-HK** [comment] 2021-05-07 21:06
Hey! I think the errors that were preventing the application from running are resolved now. Created a PR - please let me know if anything is not satisfactory !

**Comment by subhangi2731** [comment] 2021-05-12 03:09
@Aaishpra can u assign me this please

**Comment by A-HK** [comment] 2021-05-12 03:11
Hey @subhangi2731 
As you can see above, I have already sent a PR to resolve this issue.

**Comment by subhangi2731** [comment] 2021-05-12 03:15
okay @A-HK it was not merged so I thought the issue is open to be worked upon

**Closed** 2021-05-13 09:45 UTC
Labels: Level3, coding, design, enhancement, gssoc21
